management:
  endpoint:
    gateway:
      enabled: true
server:
  port: 8801
spring:
  application:
    name: springcloud-gateway
eureka:
  client:
    service-url:
      - http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    non-secure-port: 8801